### PR TITLE
Complete French translation

### PR DESCRIPTION
**Pull request by julian-poidevin**
Completed french translation at 100%.

Closes issue #699

### CODE REVIEW

**Comment by julian-poidevin** [comment]
**Please do not merge yet as I integrated my changes into my fork and want to perform a fast check before allowing to merge. Thanks**

**Comment by julian-poidevin** [comment]
It's all right, you can merge if you approve the changes 😉 .

**Comment by julian-poidevin** [comment]
@bobintetley After compiling asm3 with the new translation and running "make test", old translations are still showing.
I tried to clear the browser cache and also remove the __pycache__ remaining folders.
Do you have any clue ?

**Comment by julian-poidevin** [comment]
Seems to only be happening for the log :
image

And the menu : 
image

**Comment by bobintetley** [comment]
did you run make translation first?

**Comment by julian-poidevin** [comment]
Yes I did

**Comment by bobintetley** [comment]
Hmm, I would have thought the same as you and the browser cache is holding
the old translation. Try CTRL+R to refresh it, but if you dumped the cache
already that should have worked.

**Comment by bobintetley** [comment]
Did you get to the bottom of the issue?

**Comment by julian-poidevin** [comment]
Unfortunately not yet. I'll try to have a look a this the next few days. The translation part is complete now thought, it just seems it is not aoolyed to all "parts" of ASM3. It's up to you to decide if you wish to merge this of if you prefer that I fix the bug before merging.

**Comment by julian-poidevin** [comment]
Hello @bobintetley, starting to dig into the issue, here's my first findings :

### I first tried to understand why the issue was happening to the French langage by compairing with an other langage (`es.po` : Spanish)

I noticed both `es.po` and `fr.po` file are referencing the string `{0} {1}: reserved by {2}`

https://github.com/bobintetley/asm3/blob/6d4837aab0b46790167450a800ccaac5b3d9f12d/po/es.po#L13788-L13790

https://github.com/bobintetley/asm3/blob/6d4837aab0b46790167450a800ccaac5b3d9f12d/po/fr.po#L13634-L13636

However, I couldn't find this string in either the repo [asm.pot](https://github.com/bobintetley/asm3/blob/master/po/asm.pot) or my generated [asm.pot](https://github.com/bobintetley/asm3/blob/49e656abea7f4be7dd80311c8c2f65178091b3e0/po/asm.pot) file (using `make pot`) **is this normal and is this important** ?

I remember having some issues with untranslated sentences so I synced my branch with your master branch, regenerated the asm.pot file and then started having some issues (I uploaded the new asm.pot file in Zanata, the tool I use to translate).

Thanks.

**Comment by julian-poidevin** [comment]
Issue is now fixed. There are some strings that remains untranslated (e.g : _"Remove the country field from person details"_) but these are not appearing on the fr.po file in the repo.

You can merge to master if you accept the changes.
I'll submit a new PR in some months to fix the last translations.

Thanks.

**Comment by bobintetley** [comment]
The pot is generated from all the tokens in the code, I re-ran it after merging your pull request so that it's upto date. New strings are not automatically added to the po files, merging new strings from the pot is something your po editor should be doing and it's usually a manual step.

Thanks for all your hard work on this!

**Comment by julian-poidevin** [comment]
Thanks for the info on the PO file.
No problem for the French translation, glad to help improving ASM3!

**Pull request merged**
